# Generating a simple AR(p) process

In [15]:
import pandas as pd 
import numpy as np
from AR_specs import *

# Specifications for the number of data points

In [16]:
#Specifications for number of data points 
N = 100_001

# Modelling AR(p) process

We will generate data according to the following process 
$Y_t = \alpha_1*Y_{t-1}+\alpha_2*Y_{t-2}+...+\alpha_p*Y_{t-p} + \epsilon_t$

$\epsilon_t \overset{iid}{\sim} N(0,\sigma^2)$

In [17]:
def is_stationary(alphas):
    """Check stationarity via the companion matrix eigenvalues."""
    p = len(alphas)
    companion = np.zeros((p, p))
    companion[0, :] = alphas
    if p > 1:
        companion[1:, :-1] = np.eye(p - 1)
    return np.all(np.abs(np.linalg.eigvals(companion)) < 1)

alphas = np.array([np.random.uniform(low=ALPHA_LOWER, high=ALPHA_UPPER) for _ in range(P)])
while not is_stationary(alphas):
    alphas = np.array([np.random.uniform(low=ALPHA_LOWER, high=ALPHA_UPPER) for _ in range(P)])

lags = [i+1 for i in range(P)]

alpha_df = pd.DataFrame({'lags': lags, 'alpha': alphas})
alpha_df = alpha_df.set_index('lags')

alpha_df.to_csv('saved_data/alphas.csv')
alpha_df

         alpha
lags
1    -0.447756
2     0.785216
3    -0.214374
4    -0.487228
5     0.237313

In [18]:
Y = np.zeros(N)
eps = np.random.normal(loc=0, scale=SIGMA, size=N)

for t in range(P, N):
    Y[t] = alphas @ Y[t-P:t][::-1] + eps[t]

ts_df = pd.DataFrame({'t': np.arange(N), 'Y': Y})
ts_df = ts_df.set_index('t')
ts_df.to_csv('saved_data/ar_data.csv')

ts_df.tail(10)

               Y
t
99991  -1.892009
99992   1.703442
99993  -4.234769
99994   4.272924
99995  -5.827036
99996   5.349731
99997  -4.969152
99998   4.672782
99999  -2.942717
100000  0.643420